name: Deploy Client (Azure Static Web App)

on:
  push:
    branches:
      - main
    paths:
      - 'rudy-software-consulting/client/**'
      - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'rudy-software-consulting/client/**'
      - '.github/workflows/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Manual Run - Production'
        required: true
        default: 'Production'

jobs:
  build_and_deploy_job:
    environment: production
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies and Build
        run: |
          cd rudy-software-consulting/client
          npm ci
          npm run build

      - name: Copy staticwebapp.config.json to dist
        run: cp rudy-software-consulting/client/staticwebapp.config.json rudy-software-consulting/client/dist/staticwebapp.config.json

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_POND_03130EA10 }}
          action: "upload"
          app_location: "./rudy-software-consulting/client"
          output_location: "dist"
          api_location: ""
          github_id_token: ${{ steps.idtoken.outputs.result }}
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_EMAIL_USERNAME: ${{ secrets.VITE_EMAIL_USERNAME }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
